version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-215-41-121.compute-1.amazonaws.com
            port: 5432
            database: d3js705quh58le
            ssl: true
            user: fwwzkeaquxshfg
            password: 1d566ff3758de81ad2329f596afa43b122ea81234b5beeb4879a8a42c56ea158
            migrations: true
#   postgres:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_USER: prisma
#       POSTGRES_PASSWORD: prisma
#     volumes:
#       - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
